//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingReminder.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingReminder.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ отклонен.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлено в.
        /// </summary>
        internal static string AddedTo {
            get {
                return ResourceManager.GetString("AddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавлено к текущему списку.
        /// </summary>
        internal static string AddedToCurrentList {
            get {
                return ResourceManager.GetString("AddedToCurrentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлено в планы.
        /// </summary>
        internal static string AddedToThePlans {
            get {
                return ResourceManager.GetString("AddedToThePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый товар.
        /// </summary>
        internal static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый товар.
        /// </summary>
        internal static string AddNewPurchase {
            get {
                return ResourceManager.GetString("AddNewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить фотографии чеков.
        /// </summary>
        internal static string AddPhotosOfReceipts {
            get {
                return ResourceManager.GetString("AddPhotosOfReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить к текущему.
        /// </summary>
        internal static string AddToCurrentList {
            get {
                return ResourceManager.GetString("AddToCurrentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все товары отмечены, как купленные. Вы можете.
        /// </summary>
        internal static string AllProductsAreMarkedAsPurchasedYouCan {
            get {
                return ResourceManager.GetString("AllProductsAreMarkedAsPurchasedYouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все фото.
        /// </summary>
        internal static string AllThePhotos {
            get {
                return ResourceManager.GetString("AllThePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на уже есть в списке планов.
        /// </summary>
        internal static string AlreadyOnTheListOfPlans {
            get {
                return ResourceManager.GetString("AlreadyOnTheListOfPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при удалении.
        /// </summary>
        internal static string AnErrorOccurredWhileUninstalling {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камера не доступна.
        /// </summary>
        internal static string CameraNotAvailable {
            get {
                return ResourceManager.GetString("CameraNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать тему оформления.
        /// </summary>
        internal static string ChooseATheme {
            get {
                return ResourceManager.GetString("ChooseATheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить текущий список покупок.
        /// </summary>
        internal static string ClearCurrentShoppingList {
            get {
                return ResourceManager.GetString("ClearCurrentShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить группы.
        /// </summary>
        internal static string ClearTheGroups {
            get {
                return ResourceManager.GetString("ClearTheGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить историю.
        /// </summary>
        internal static string ClearTheHistory {
            get {
                return ResourceManager.GetString("ClearTheHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить планы.
        /// </summary>
        internal static string ClearThePlans {
            get {
                return ResourceManager.GetString("ClearThePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить покупку.
        /// </summary>
        internal static string CompleteThePurchase {
            get {
                return ResourceManager.GetString("CompleteThePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новую группу.
        /// </summary>
        internal static string CreateNewGroup {
            get {
                return ResourceManager.GetString("CreateNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить все.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить фото.
        /// </summary>
        internal static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить фотографии прикрепленные к данному списку.
        /// </summary>
        internal static string DeletePhotosAttachedToThisList {
            get {
                return ResourceManager.GetString("DeletePhotosAttachedToThisList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить фотографии.
        /// </summary>
        internal static string DeleteThePhotos {
            get {
                return ResourceManager.GetString("DeleteThePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить данный список из истории покупок.
        /// </summary>
        internal static string DeleteThisListFromPurchaseHistory {
            get {
                return ResourceManager.GetString("DeleteThisListFromPurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить данную группу товаров.
        /// </summary>
        internal static string DeleteThisProductGroup {
            get {
                return ResourceManager.GetString("DeleteThisProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указывать.
        /// </summary>
        internal static string DoNotIndicate {
            get {
                return ResourceManager.GetString("DoNotIndicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название для группы.
        /// </summary>
        internal static string EnterANameForTheGoup {
            get {
                return ResourceManager.GetString("EnterANameForTheGoup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название, которого еще нет в списке.
        /// </summary>
        internal static string EnterANameThatIsNotYetListed {
            get {
                return ResourceManager.GetString("EnterANameThatIsNotYetListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название магазина.
        /// </summary>
        internal static string EnterStoreName {
            get {
                return ResourceManager.GetString("EnterStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущие покупки.
        /// </summary>
        internal static string FICurrentPurcases {
            get {
                return ResourceManager.GetString("FICurrentPurcases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ввести полученный список.
        /// </summary>
        internal static string FIEnterReceivedList {
            get {
                return ResourceManager.GetString("FIEnterReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группы.
        /// </summary>
        internal static string FIGroups {
            get {
                return ResourceManager.GetString("FIGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История покупок.
        /// </summary>
        internal static string FIHistory {
            get {
                return ResourceManager.GetString("FIHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните название.
        /// </summary>
        internal static string FillTheName {
            get {
                return ResourceManager.GetString("FillTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запланированные.
        /// </summary>
        internal static string FIPlans {
            get {
                return ResourceManager.GetString("FIPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценить приложение.
        /// </summary>
        internal static string FIRateApp {
            get {
                return ResourceManager.GetString("FIRateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string FISettings {
            get {
                return ResourceManager.GetString("FISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активные покупки.
        /// </summary>
        internal static string FITActivePurchases {
            get {
                return ResourceManager.GetString("FITActivePurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История покупок.
        /// </summary>
        internal static string FITHistoryOfPurchases {
            get {
                return ResourceManager.GetString("FITHistoryOfPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фото.
        /// </summary>
        internal static string FITPhotos {
            get {
                return ResourceManager.GetString("FITPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купленные.
        /// </summary>
        internal static string FITPurcased {
            get {
                return ResourceManager.GetString("FITPurcased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из списка.
        /// </summary>
        internal static string FromTheList {
            get {
                return ResourceManager.GetString("FromTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из списка групп.
        /// </summary>
        internal static string FromTheListOfGroups {
            get {
                return ResourceManager.GetString("FromTheListOfGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на уже имеется в списке.
        /// </summary>
        internal static string IsAlreadyInTheList {
            get {
                return ResourceManager.GetString("IsAlreadyInTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позже.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список пуст.
        /// </summary>
        internal static string ListIsEmpty {
            get {
                return ResourceManager.GetString("ListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сделать данную группу активным списком?.
        /// </summary>
        internal static string MakeThitGroupAnActiveList {
            get {
                return ResourceManager.GetString("MakeThitGroupAnActiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переммещено в группу.
        /// </summary>
        internal static string MovedToGroup {
            get {
                return ResourceManager.GetString("MovedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещено в планы.
        /// </summary>
        internal static string MovedToPlans {
            get {
                return ResourceManager.GetString("MovedToPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно купить.
        /// </summary>
        internal static string NeedToBuy {
            get {
                return ResourceManager.GetString("NeedToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С данной покупкой не было сделано ни одной фотографии чеков.
        /// </summary>
        internal static string NoCheckPhotosHaveBeenTakenWithThisPurchase {
            get {
                return ResourceManager.GetString("NoCheckPhotosHaveBeenTakenWithThisPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все покупки завершены. Какие из них сохранить.
        /// </summary>
        internal static string NotAllPurchasesAreCompletedWhichOnesToSave {
            get {
                return ResourceManager.GetString("NotAllPurchasesAreCompletedWhichOnesToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано.
        /// </summary>
        internal static string NotIndicated {
            get {
                return ResourceManager.GetString("NotIndicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ок.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставьте полученое от другого пользователя скопированное сообщение.
        /// </summary>
        internal static string PasteTheCopiedMessageReceivedFromAnotherUser {
            get {
                return ResourceManager.GetString("PasteTheCopiedMessageReceivedFromAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фото.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотографии были удалены.
        /// </summary>
        internal static string PhotosHaveBeenDeleted {
            get {
                return ResourceManager.GetString("PhotosHaveBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запланированная покупка.
        /// </summary>
        internal static string PlannedPurchase {
            get {
                return ResourceManager.GetString("PlannedPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукты.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чеки покупок от.
        /// </summary>
        internal static string PurchaseReceiptsFrom {
            get {
                return ResourceManager.GetString("PurchaseReceiptsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценить.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить из списка.
        /// </summary>
        internal static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить этот предмет из списка.
        /// </summary>
        internal static string RemoveThiItemFromTheList {
            get {
                return ResourceManager.GetString("RemoveThiItemFromTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить этим списком.
        /// </summary>
        internal static string ReplaceWithThisList {
            get {
                return ResourceManager.GetString("ReplaceWithThisList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить этим списком, а активный сохранить в новую группу.
        /// </summary>
        internal static string ReplaceWithThisListAndSaveTheActiveListInANewGroup {
            get {
                return ResourceManager.GetString("ReplaceWithThisListAndSaveTheActiveListInANewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить все.
        /// </summary>
        internal static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить завершенные, а оставшиеся перенести на следующую покупку.
        /// </summary>
        internal static string SaveCompletedAndTransferTheRemainingToTheNextPurchase {
            get {
                return ResourceManager.GetString("SaveCompletedAndTransferTheRemainingToTheNextPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить только завершенные.
        /// </summary>
        internal static string SaveOnlyCmpleted {
            get {
                return ResourceManager.GetString("SaveOnlyCmpleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передать.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поделиться группой.
        /// </summary>
        internal static string ShareAGroup {
            get {
                return ResourceManager.GetString("ShareAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поделиться текущим списком покупок.
        /// </summary>
        internal static string ShareYourCurrentShoppingList {
            get {
                return ResourceManager.GetString("ShareYourCurrentShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список пуст. Оперция отменена.
        /// </summary>
        internal static string TheListIsEmptyTheOperationWasCanceled {
            get {
                return ResourceManager.GetString("TheListIsEmptyTheOperationWasCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В памяти содержится список. Куда его отправить.
        /// </summary>
        internal static string TheMemoryContainsAListWhereToSendIt {
            get {
                return ResourceManager.GetString("TheMemoryContainsAListWhereToSendIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего.
        /// </summary>
        internal static string ThereAre {
            get {
                return ResourceManager.GetString("ThereAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В активном списке есть элементы..
        /// </summary>
        internal static string ThereAreItemsInTheActiveList {
            get {
                return ResourceManager.GetString("ThereAreItemsInTheActiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет ни товаров, ни фотографий чеков для сохранения. Сохранение невозможно.
        /// </summary>
        internal static string ThereAreNoGoodsOrPhotosOfReceiptsToSaveSavingIsNotPossible {
            get {
                return ResourceManager.GetString("ThereAreNoGoodsOrPhotosOfReceiptsToSaveSavingIsNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет фотографий.
        /// </summary>
        internal static string ThereAreNoPhotos {
            get {
                return ResourceManager.GetString("ThereAreNoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В списке нет ни одного товара. Сохранить только фото.
        /// </summary>
        internal static string ThereAreNoProductsInTheListSaveOnlyPhoto {
            get {
                return ResourceManager.GetString("ThereAreNoProductsInTheListSaveOnlyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В памяти нет подходящего списка. Откройте присланное сообщение и скопируйте его в буфер обмена.
        /// </summary>
        internal static string ThereIsNoSuitableListInMemoryOpenTheSentMessageAndCopyItToTheClipboard {
            get {
                return ResourceManager.GetString("ThereIsNoSuitableListInMemoryOpenTheSentMessageAndCopyItToTheClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название не может быть пустым.
        /// </summary>
        internal static string TitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("TitleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В активны список.
        /// </summary>
        internal static string ToActiveList {
            get {
                return ResourceManager.GetString("ToActiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для полного применения темы необходимо перезапустить приложение.
        /// </summary>
        internal static string ToFullyApplyTheThemeYouMustRestartTheApplication {
            get {
                return ResourceManager.GetString("ToFullyApplyTheThemeYouMustRestartTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В планы.
        /// </summary>
        internal static string ToPlans {
            get {
                return ResourceManager.GetString("ToPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необратотанная страница.
        /// </summary>
        internal static string UnhandledPage {
            get {
                return ResourceManager.GetString("UnhandledPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ед. измерения.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шт,Кг,Упак,л.
        /// </summary>
        internal static string UnitsList {
            get {
                return ResourceManager.GetString("UnitsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на уже были в списке.
        /// </summary>
        internal static string WereAlreadyOnTheList {
            get {
                return ResourceManager.GetString("WereAlreadyOnTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на уже были в списке.
        /// </summary>
        internal static string WereAlredyOnTheList {
            get {
                return ResourceManager.GetString("WereAlredyOnTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без названия.
        /// </summary>
        internal static string WithoutTitle {
            get {
                return ResourceManager.GetString("WithoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете оценить приложение. Это поможет его продвижению.
        /// </summary>
        internal static string YouCanRateTheAppThisWillHelpToPromoteIt {
            get {
                return ResourceManager.GetString("YouCanRateTheAppThisWillHelpToPromoteIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это сообщение можно использовать в приложении ShoppingReminder, скопировав его.
        /// </summary>
        internal static string YouCanUseThisMessageInTheShoppingRemnderApplicationByCopyingIt {
            get {
                return ResourceManager.GetString("YouCanUseThisMessageInTheShoppingRemnderApplicationByCopyingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше устройство не поддерживает эту функцию.
        /// </summary>
        internal static string YourDeviceDoesNotSupportThisFeature {
            get {
                return ResourceManager.GetString("YourDeviceDoesNotSupportThisFeature", resourceCulture);
            }
        }
    }
}
